spring:
  application:
    name: security-lib

security:
  jwt:
    issuer: food-ordering-system
    hs256-secret-base64: ${JWT_SECRET_BASE64}
    expiration: 3600

pii:
  aes:
    key-base64: ${AES_KEY_BASE64}